test-case:
  name: Positive Test for has-cloud-deployment-model
  description: Test that an SSP system-characteristics element has a prop element with a name attribute equal to "cloud-deployment-model".
  content: ../content/FedRAMP-SSP-Example.OSCAL.xml
  expectations:
    - constraint-id: has-cloud-deployment-model
      result: pass
