test-case:
  name: Positive Test for has-cloud-deployment-model-remarks
  description: Test that every SSP system-characteristics prop element with a name attribute equal to "cloud-deployment-model" and a value attribute equal to "hybrid-cloud" has a remarks element.
  content: ../content/ssp-all-VALID.xml
  expectations:
    - constraint-id: has-cloud-deployment-model-remarks
      result: pass
