test-case:
  name: Negative Test for has-configuration-management-plan
  description: >-
    This test case validates the behavior of constraint
    has-configuration-management-plan
  content: ../content/ssp-has-configuration-management-plan-INVALID.xml
  expectations:
    - constraint-id: has-configuration-management-plan
      result: fail
