# Driver for the valid inventory-item-has-one-baseline-configuration-name constraint unit test.
test-case:
  name: The valid inventory-item-has-one-baseline-configuration-name constraint unit test.
  description: Test that every infrastructure inventory item has only one baseline-configuration-name property.
  content: ../content/ssp-all-VALID.xml
  expectations:
  - constraint-id: inventory-item-has-one-baseline-configuration-name
    result: pass