FROM node:18.12.1-slim

WORKDIR /code/src/examples/javascript
ADD package.json /code/src/examples/javascript/package.json
ADD package-lock.json /code/src/examples/javascript/package-lock.json
RUN npm i
