# This action runs unit tests for the OSCAL (schematron) validations to ensure validations
# are working against known samples
name: "OSCAL Validations: Unit Tests"

# Triggered when code is pushed to master and on pull requests
on:
  push:
    branches:
      - master
      - develop
      - 'feature**'  # This will match any branch starting with "feature"

  pull_request:

# the job requires some dependencies to be installed (including submodules), runs the tests, and then reports results
jobs:
  # one job that runs tests
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    # Checkout repository and its submodules
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Install required node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
      - name: Install OSCAL CLI
        run: |
          make init-validations
      - name: Run Cucumber tests
        shell: bash
        run: |
          make build-validations
      - name : Publish all Junit XML tests results in Github Summary
        uses: test-summary/action@v2
        if: always()
        with:
            paths: |
              **/reports/junit-*.xml